import './global.css';

import localFont from 'next/font/local';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

const font = localFont({
  src: [
    {
      path: './fonts/BeVietnamPro-Light.ttf',
      weight: '300',
    },
    {
      path: './fonts/BeVietnamPro-Regular.ttf',
      weight: '400',
    },
    {
      path: './fonts/BeVietnamPro-Medium.ttf',
      weight: '500',
    },
    {
      path: './fonts/BeVietnamPro-SemiBold.ttf',
      weight: '600',
    },
    {
      path: './fonts/BeVietnamPro-Bold.ttf',
      weight: '700',
    },
  ],
  display: 'swap',
  variable: '--font-be-vietnam-pro',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} ${font.variable}`}>{children}</body>
    </html>
  );
}
