import './global.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { Header } from '@mmcinema-ui/web-ui';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: '#d42987',
              },
              components: {
                Dropdown: {
                  controlItemBgHover: '#fef1f8',
                },
              },
            }}
          >
            <Header />
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
